export type S1Rarity =
  | "ROOKIE"
  | "CHALLENGER"
  | "CHAMPION"
  | "WORLD_CLASS"
  | "LEGENDS";

export interface S1CardSeed {
  id: string;
  name: string;
  game: string;
  nationality: string;
  role: string;
  team: string;
  rarity: S1Rarity;
}

export const s1Series = {
  name: "Rift Champions",
  slug: "rift-champions",
  code: "S1",
  coverImage: "/src/assets/series/rift-champions.jpg",
} as const;

export const s1Cards: S1CardSeed[] = [
  {
    id: "S1-01",
    name: "Vadius",
    game: "LoL",
    nationality: "France",
    role: "Support",
    team: "GameWard",
    rarity: "ROOKIE",
  },
  {
    id: "S1-02",
    name: "Daglas",
    game: "LoL",
    nationality: "Lituanie",
    role: "Jungler",
    team: "Vitality",
    rarity: "ROOKIE",
  },
  {
    id: "S1-03",
    name: "Fresskowy",
    game: "LoL",
    nationality: "Pologne",
    role: "Midlaner",
    team: "MAD Lions KOI",
    rarity: "ROOKIE",
  },
  {
    id: "S1-04",
    name: "Heng",
    game: "LoL",
    nationality: "Chine",
    role: "Jungler",
    team: "Team WE",
    rarity: "ROOKIE",
  },
  {
    id: "S1-05",
    name: "Isma",
    game: "LoL",
    nationality: "France",
    role: "Jungler",
    team: "SK Gaming",
    rarity: "ROOKIE",
  },
  {
    id: "S1-06",
    name: "Karis",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "Midlaner",
    team: "Kwangdong",
    rarity: "ROOKIE",
  },
  {
    id: "S1-07",
    name: "Jun",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "Support",
    team: "Fnatic",
    rarity: "ROOKIE",
  },
  {
    id: "S1-08",
    name: "Busio",
    game: "LoL",
    nationality: "USA",
    role: "Support",
    team: "FlyQuest",
    rarity: "ROOKIE",
  },
  {
    id: "S1-09",
    name: "Jackies",
    game: "LoL",
    nationality: "Rép. Tchèque",
    role: "Midlaner",
    team: "GiantX",
    rarity: "ROOKIE",
  },
  {
    id: "S1-10",
    name: "Massu",
    game: "LoL",
    nationality: "Canada",
    role: "ADC",
    team: "FlyQuest",
    rarity: "ROOKIE",
  },
  {
    id: "S1-11",
    name: "Alvaro",
    game: "LoL",
    nationality: "Espagne",
    role: "Support",
    team: "MAD Lions KOI",
    rarity: "ROOKIE",
  },
  {
    id: "S1-12",
    name: "Supa",
    game: "LoL",
    nationality: "Espagne",
    role: "ADC",
    team: "MAD Lions KOI",
    rarity: "ROOKIE",
  },
  {
    id: "S1-13",
    name: "Irrelevant",
    game: "LoL",
    nationality: "Allemagne",
    role: "Toplaner",
    team: "SK Gaming",
    rarity: "ROOKIE",
  },
  {
    id: "S1-14",
    name: "VicLa",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "Midlaner",
    team: "KT Rolster",
    rarity: "ROOKIE",
  },
  {
    id: "S1-15",
    name: "Vetheo",
    game: "LoL",
    nationality: "France",
    role: "Midlaner",
    team: "Team Vitality",
    rarity: "ROOKIE",
  },
  {
    id: "S1-16",
    name: "Exakick",
    game: "LoL",
    nationality: "France",
    role: "ADC",
    team: "SK Gaming",
    rarity: "ROOKIE",
  },
  {
    id: "S1-17",
    name: "Shanji",
    game: "LoL",
    nationality: "Chine",
    role: "Toplaner",
    team: "NIP",
    rarity: "ROOKIE",
  },
  {
    id: "S1-18",
    name: "Tangyuan",
    game: "LoL",
    nationality: "Chine",
    role: "Midlaner",
    team: "RNG",
    rarity: "ROOKIE",
  },
  {
    id: "S1-19",
    name: "Jojopyun",
    game: "LoL",
    nationality: "Canada",
    role: "Midlaner",
    team: "Cloud9",
    rarity: "ROOKIE",
  },
  {
    id: "S1-20",
    name: "APA",
    game: "LoL",
    nationality: "USA",
    role: "Midlaner",
    team: "Team Liquid",
    rarity: "ROOKIE",
  },
  {
    id: "S1-21",
    name: "Oscarinin",
    game: "LoL",
    nationality: "Espagne",
    role: "Toplaner",
    team: "Fnatic",
    rarity: "ROOKIE",
  },
  {
    id: "S1-22",
    name: "Adam",
    game: "LoL",
    nationality: "France",
    role: "Toplaner",
    team: "Team BDS",
    rarity: "ROOKIE",
  },
  {
    id: "S1-23",
    name: "Thanatos",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "Toplaner",
    team: "Cloud9",
    rarity: "ROOKIE",
  },
  {
    id: "S1-24",
    name: "Milkyway",
    game: "LoL",
    nationality: "Chine",
    role: "Jungler",
    team: "FPX",
    rarity: "ROOKIE",
  },
  {
    id: "S1-25",
    name: "Lucid",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "Jungler",
    team: "Dplus KIA",
    rarity: "ROOKIE",
  },
  {
    id: "S1-26",
    name: "Bull",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "ADC",
    team: "Kwangdong",
    rarity: "ROOKIE",
  },
  {
    id: "S1-27",
    name: "Quid",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "Midlaner",
    team: "100 Thieves",
    rarity: "ROOKIE",
  },
  {
    id: "S1-28",
    name: "Yike",
    game: "LoL",
    nationality: "Suède",
    role: "Jungler",
    team: "G2 Esports",
    rarity: "ROOKIE",
  },
  {
    id: "S1-29",
    name: "Sheo",
    game: "LoL",
    nationality: "France",
    role: "Jungler",
    team: "Team BDS",
    rarity: "ROOKIE",
  },
  {
    id: "S1-30",
    name: "Peyz",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "ADC",
    team: "Gen.G",
    rarity: "ROOKIE",
  },
  {
    id: "S1-31",
    name: "Caliste",
    game: "LoL",
    nationality: "France",
    role: "ADC",
    team: "Karmine Corp",
    rarity: "ROOKIE",
  },
  {
    id: "S1-32",
    name: "Zeka",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "Midlaner",
    team: "Hanwha Life",
    rarity: "ROOKIE",
  },
  {
    id: "S1-33",
    name: "BrokenBlade",
    game: "LoL",
    nationality: "Allemagne",
    role: "Toplaner",
    team: "G2 Esports",
    rarity: "CHALLENGER",
  },
  {
    id: "S1-34",
    name: "Hylissang",
    game: "LoL",
    nationality: "Bulgarie",
    role: "Support",
    team: "Vitality",
    rarity: "CHALLENGER",
  },
  {
    id: "S1-35",
    name: "Humanoid",
    game: "LoL",
    nationality: "Rép. Tchèque",
    role: "Midlaner",
    team: "Fnatic",
    rarity: "CHALLENGER",
  },
  {
    id: "S1-36",
    name: "Razork",
    game: "LoL",
    nationality: "Espagne",
    role: "Jungler",
    team: "Fnatic",
    rarity: "CHALLENGER",
  },
  {
    id: "S1-37",
    name: "Blaber",
    game: "LoL",
    nationality: "USA",
    role: "Jungler",
    team: "Cloud9",
    rarity: "CHALLENGER",
  },
  {
    id: "S1-38",
    name: "CoreJJ",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "Support",
    team: "Team Liquid",
    rarity: "CHALLENGER",
  },
  {
    id: "S1-39",
    name: "Elyoya",
    game: "LoL",
    nationality: "Espagne",
    role: "Jungler",
    team: "MAD Lions",
    rarity: "CHALLENGER",
  },
  {
    id: "S1-40",
    name: "Xiaohu",
    game: "LoL",
    nationality: "Chine",
    role: "Midlaner",
    team: "Weibo Gaming",
    rarity: "CHALLENGER",
  },
  {
    id: "S1-41",
    name: "Impact",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "Toplaner",
    team: "Team Liquid",
    rarity: "CHALLENGER",
  },
  {
    id: "S1-42",
    name: "369",
    game: "LoL",
    nationality: "Chine",
    role: "Toplaner",
    team: "TES",
    rarity: "CHALLENGER",
  },
  {
    id: "S1-43",
    name: "Peanut",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "Jungler",
    team: "Hanwha Life",
    rarity: "CHALLENGER",
  },
  {
    id: "S1-44",
    name: "Mikyx",
    game: "LoL",
    nationality: "Slovénie",
    role: "Support",
    team: "G2 Esports",
    rarity: "CHALLENGER",
  },
  {
    id: "S1-45",
    name: "Hans Sama",
    game: "LoL",
    nationality: "France",
    role: "ADC",
    team: "G2 Esports",
    rarity: "CHALLENGER",
  },
  {
    id: "S1-46",
    name: "Viper",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "ADC",
    team: "Hanwha Life",
    rarity: "CHALLENGER",
  },
  {
    id: "S1-47",
    name: "Knight",
    game: "LoL",
    nationality: "Chine",
    role: "Midlaner",
    team: "BLG",
    rarity: "CHALLENGER",
  },
  {
    id: "S1-48",
    name: "Bin",
    game: "LoL",
    nationality: "Chine",
    role: "Toplaner",
    team: "BLG",
    rarity: "CHALLENGER",
  },
  {
    id: "S1-49",
    name: "Jankos",
    game: "LoL",
    nationality: "Pologne",
    role: "Jungler",
    team: "G2 Esports",
    rarity: "CHALLENGER",
  },
  {
    id: "S1-50",
    name: "Ruler",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "ADC",
    team: "JDG",
    rarity: "CHALLENGER",
  },
  {
    id: "S1-51",
    name: "Oner",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "Jungler",
    team: "T1",
    rarity: "CHALLENGER",
  },
  {
    id: "S1-52",
    name: "Gumayusi",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "ADC",
    team: "T1",
    rarity: "CHALLENGER",
  },
  {
    id: "S1-53",
    name: "Tian",
    game: "LoL",
    nationality: "Chine",
    role: "Jungler",
    team: "FPX",
    rarity: "CHAMPION",
  },
  {
    id: "S1-54",
    name: "Doublelift",
    game: "LoL",
    nationality: "USA",
    role: "ADC",
    team: "Team Liquid",
    rarity: "CHAMPION",
  },
  {
    id: "S1-55",
    name: "Meiko",
    game: "LoL",
    nationality: "Chine",
    role: "Support",
    team: "EDG",
    rarity: "CHAMPION",
  },
  {
    id: "S1-56",
    name: "Rekkles",
    game: "LoL",
    nationality: "Suède",
    role: "ADC",
    team: "Fnatic",
    rarity: "CHAMPION",
  },
  {
    id: "S1-57",
    name: "Chovy",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "Midlaner",
    team: "Gen.G",
    rarity: "CHAMPION",
  },
  {
    id: "S1-58",
    name: "Scout",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "Midlaner",
    team: "EDG",
    rarity: "CHAMPION",
  },
  {
    id: "S1-59",
    name: "JackeyLove",
    game: "LoL",
    nationality: "Chine",
    role: "ADC",
    team: "Invictus Gaming",
    rarity: "CHAMPION",
  },
  {
    id: "S1-60",
    name: "TheShy",
    game: "LoL",
    nationality: "Chine",
    role: "Toplaner",
    team: "Invictus Gaming",
    rarity: "CHAMPION",
  },
  {
    id: "S1-61",
    name: "Zeus",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "Toplaner",
    team: "T1",
    rarity: "CHAMPION",
  },
  {
    id: "S1-62",
    name: "Keria",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "Support",
    team: "T1",
    rarity: "CHAMPION",
  },
  {
    id: "S1-63",
    name: "BeryL",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "Support",
    team: "DRX",
    rarity: "WORLD_CLASS",
  },
  {
    id: "S1-64",
    name: "Canyon",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "Jungler",
    team: "Damwon Gaming",
    rarity: "WORLD_CLASS",
  },
  {
    id: "S1-65",
    name: "ShowMaker",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "Midlaner",
    team: "Damwon Gaming",
    rarity: "WORLD_CLASS",
  },
  {
    id: "S1-66",
    name: "Perkz",
    game: "LoL",
    nationality: "Croatie",
    role: "Midlaner",
    team: "G2 Esports",
    rarity: "WORLD_CLASS",
  },
  {
    id: "S1-67",
    name: "Rookie",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "Midlaner",
    team: "Invictus Gaming",
    rarity: "WORLD_CLASS",
  },
  {
    id: "S1-68",
    name: "Uzi",
    game: "LoL",
    nationality: "Chine",
    role: "ADC",
    team: "RNG",
    rarity: "WORLD_CLASS",
  },
  {
    id: "S1-69",
    name: "Caps",
    game: "LoL",
    nationality: "Danemark",
    role: "Midlaner",
    team: "G2 Esports",
    rarity: "WORLD_CLASS",
  },
  {
    id: "S1-70",
    name: "Faker",
    game: "LoL",
    nationality: "Corée du Sud",
    role: "Midlaner",
    team: "T1",
    rarity: "LEGENDS",
  },
];
